Initial commit for dsc on deepmind control suite, reacher task, pixel…
abagaria/skill-chaining pull request #2
Opened 2020-02-12 23:36 UTC by ktan38

… observation.

2020-02-13 00:29 UTC, abagaria requested changes
This is looking good lets make the minor edits i have mentioned and make another PR

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/ddpg/DDPGAgentClass.py
> +            self.actor = ConvActor(4, state_size, action_size, device=device)
Make the `in_channels` an input to the DDPG class as `frame_stack` or something like that

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/ddpg/model.py
> +        self.linear1 = nn.Linear(98*64+action_dim, 200)
Can we add a comment here showing how we got 98*64?

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/ddpg/replay_buffer.py
> +        #assert isinstance(state, np.ndarray), "state"
lets bring this assert statement back, we should only have `np.ndarray`'s inside the replay buffer!

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/OptionClass.py
> +			if self.name == "global_option":
Try to revert this to the old logic for initialize_with_global_ddpg()

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/OptionClass.py
> +				if reward:
Dont check for `reward` in this fashion, can screw us when the reward function is not 0 vs 1

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/OptionClass.py
> +			examples = [(np.array(segmented_state.features())[-1, :, :]) for segmented_state in segmented_states]
Can we add a convenience function inside the OptionClass that takes a state object and returns a numpy array which represents the input the initiation classifier.

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/OptionClass.py
> +			examples = [(np.array(segmented_state.features())[-1, :, :]) for segmented_state in segmented_states]
For example:

`def f(x, n):
    return x[-n, ...]`

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/OptionClass.py
> +			examples = [(np.array(segmented_state.features())[-1, :, :]) for segmented_state in segmented_states]
Also, maybe add a comment on why the tuple-ing was needed?

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/OptionClass.py
>  		sampled_states = random.sample(states, k=num_positive_examples)
Note for the future: we dont want to sample the same number of negatives as positives. We want to add a scaling term to the loss function instead so as to not lose the correct topology of the initiation set classifier.

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/SkillChainingAgentClass.py
> +from OptionClass import Option
we shouldn't need this

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/SkillChainingAgentClass.py
> +										   use_double_dqn=True, writer=self.writer, device=self.device)
Here, can we say `pixel_observation=self.mdp.pixel_observation` or as an argument to the DSC class

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/SkillChainingAgentClass.py
> +			q_value = global_solver.get_qvalue(state.features(), option_idx)
Make sure that `state.features()` is still a `np.array`. I think it is a `LazyFrame` or `FrameStack` thing rn

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/SkillChainingAgentClass.py
> +		overall_mdp = FixedReacherMDP(seed=args.seed, difficulty="hard", render=args.render)
revert

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/SkillChainingAgentClass.py
> +		overall_mdp = GymMDP(args.env, render=args.render)
revert

2020-02-13 00:29 UTC, abagaria commented on simple_rl/agents/func_approx/dsc/utils.py
> +def plot_one_class_initiation_images(option, episode=None, experiment_name=""):
set `xlim()` and `ylim()` using the bounds in the DMControlClass

2020-02-13 00:29 UTC, abagaria commented on simple_rl/tasks/gym/wrappers.py
> +        return (LazyFrames(list(self.frames), self.lz4_compress))
lets not do this, lets fix whatever breaks while keeping this constant

2020-02-13 00:29 UTC, abagaria commented on simple_rl/tasks/gym/wrappers.py
> +        return (LazyFrames(list(self.frames), self.lz4_compress))
this is *probably* prematurely evaluating the LazyFrame object

2020-02-13 00:29 UTC, abagaria commented on simple_rl/tasks/gym/wrappers.py
> +        #self.realframes = deque(maxlen=num_stack)
lets not modify the gym wrappers unless absolutely necessary.

2020-02-13 00:29 UTC, abagaria commented on simple_rl/tasks/gym/wrappers.py
> +        observation = np.divide(observation[0] + observation[1] + observation[2], 3.0)
The grayscale operation should not happen inside this wrapper. Either we find a Grayscale gym wrapper, or write it as a clean function in this same class

2020-02-24 22:36 UTC, ktan38 commented on simple_rl/agents/func_approx/ddpg/replay_buffer.py
> +        #assert isinstance(state, np.ndarray), "state"
we want to store lazyframes in there, will put appropriate assert statement in here

2020-02-26 07:53 UTC, closed without merging